name = "equivio"
compatibility_date = "2025-02-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

# KV Namespace usage if needed later
# [[kv_namespaces]]
# binding = "NEXT_CACHE_WORKERS_KV"
# id = "<KV_ID>"
# Environment Variables (Non-sensitive)
[vars]
SMTP_HOST = "brun.o2switch.net"
SMTP_PORT = "465"
SMTP_SECURE = "true"
SMTP_USER = "contact@equivio.fr"
CLAIMS_ADMIN_EMAIL = "contact@equivio.fr"
