name = "equivio"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"
assets = { directory = ".open-next/assets", binding = "ASSETS" }

# KV Namespace usage if needed later
# [[kv_namespaces]]
# binding = "NEXT_CACHE_WORKERS_KV"
# id = "<KV_ID>"
